# Adapted from python-money:
# https://github.com/poswald/python-money
import re
from collections import namedtuple, defaultdict

Currency = namedtuple('Currency', ['symbol', 'name'])

currency_identifiers = {}

iso_currency_re = re.compile('iso4217_?[A-Z]{3}')


def possible_currency_from_unit_ref(unit_ref):
    yield unit_ref[:3]
    yield unit_ref[-3:]
    iso_match = iso_currency_re.search(unit_ref)
    if iso_match:
        yield iso_match.group()[-3:]


def find_currency(unit_ref):
    unit_ref = unit_ref.upper()

    for possible_currency in possible_currency_from_unit_ref(unit_ref):
        if possible_currency in currency_identifiers:
            return currency_identifiers[possible_currency]


currency_identifiers['AED'] = Currency(u'', u'UAE Dirham')
currency_identifiers['AFN'] = Currency(u'؋', u'Afghani')
currency_identifiers['ALL'] = Currency(u'Lek', u'Lek')
currency_identifiers['AMD'] = Currency(u'', u'Armenian Dram')
currency_identifiers['ANG'] = Currency(u'ƒ', u'Netherlands Antillean Guilder')
currency_identifiers['AOA'] = Currency(u'', u'Kwanza')
currency_identifiers['ARS'] = Currency(u'$', u'Argentine Peso')
currency_identifiers['AUD'] = Currency(u'$', u'Australian Dollar')
currency_identifiers['AWG'] = Currency(u'ƒ', u'Aruban Florin')
currency_identifiers['AZN'] = Currency(u'ман', u'Azerbaijanian Manat')
currency_identifiers['BAM'] = Currency(u'KM', u'Convertible Mark')
currency_identifiers['BBD'] = Currency(u'$', u'Barbados Dollar')
currency_identifiers['BDT'] = Currency(u'', u'Taka')
currency_identifiers['BGN'] = Currency(u'лв', u'Bulgarian Lev')
currency_identifiers['BHD'] = Currency(u'', u'Bahraini Dinar')
currency_identifiers['BIF'] = Currency(u'', u'Burundi Franc')
currency_identifiers['BMD'] = Currency(u'$', u'Bermudian Dollar')
currency_identifiers['BND'] = Currency(u'$', u'Brunei Dollar')
currency_identifiers['BOB'] = Currency(u'$b', u'Boliviano')
currency_identifiers['BOV'] = Currency(u'', u'Mvdol')
currency_identifiers['BRL'] = Currency(u'R$', u'Brazilian Real')
currency_identifiers['BSD'] = Currency(u'$', u'Bahamian Dollar')
currency_identifiers['BTN'] = Currency(u'', u'Ngultrum')
currency_identifiers['BWP'] = Currency(u'P', u'Pula')
currency_identifiers['BYR'] = Currency(u'p.', u'Belarussian Ruble')
currency_identifiers['BZD'] = Currency(u'BZ$', u'Belize Dollar')
currency_identifiers['CAD'] = Currency(u'$', u'Canadian Dollar')
currency_identifiers['CDF'] = Currency(u'', u'Congolese Franc')
currency_identifiers['CHE'] = Currency(u'', u'WIR Euro')
currency_identifiers['CHF'] = Currency(u'Fr.', u'Swiss Franc')
currency_identifiers['CHW'] = Currency(u'', u'WIR Franc')
currency_identifiers['CLF'] = Currency(u'', u'Unidades de fomento')
currency_identifiers['CLP'] = Currency(u'$', u'Chilean Peso')
currency_identifiers['CNY'] = Currency(u'¥', u'Yuan Renminbi')
currency_identifiers['COP'] = Currency(u'$', u'Colombian Peso')
currency_identifiers['COU'] = Currency(u'', u'Unidad de Valor Real')
currency_identifiers['CRC'] = Currency(u'₡', u'Costa Rican Colon')
currency_identifiers['CUC'] = Currency(u'', u'Peso Convertible')
currency_identifiers['CUP'] = Currency(u'₱', u'Cuban Peso')
currency_identifiers['CVE'] = Currency(u'', u'Cape Verde Escudo')
currency_identifiers['CZK'] = Currency(u'Kč', u'Czech Koruna')
currency_identifiers['DJF'] = Currency(u'', u'Djibouti Franc')
currency_identifiers['DKK'] = Currency(u'kr', u'Danish Krone')
currency_identifiers['DOP'] = Currency(u'RD$', u'Dominican Peso')
currency_identifiers['DZD'] = Currency(u'', u'Algerian Dinar')
currency_identifiers['EGP'] = Currency(u'£', u'Egyptian Pound')
currency_identifiers['ERN'] = Currency(u'', u'Nakfa')
currency_identifiers['ETB'] = Currency(u'', u'Ethiopian Birr')
currency_identifiers['EUR'] = Currency(u'€', u'Euro')
currency_identifiers['FJD'] = Currency(u'$', u'Fiji Dollar')
currency_identifiers['FKP'] = Currency(u'£', u'Falkland Islands Pound')
currency_identifiers['GBP'] = Currency(u'£', u'Pound Sterling')
currency_identifiers['GEL'] = Currency(u'', u'Lari')
currency_identifiers['GHS'] = Currency(u'', u'Ghana Cedi')
currency_identifiers['GIP'] = Currency(u'£', u'Gibraltar Pound')
currency_identifiers['GMD'] = Currency(u'', u'Dalasi')
currency_identifiers['GNF'] = Currency(u'', u'Guinea Franc')
currency_identifiers['GTQ'] = Currency(u'Q', u'Quetzal')
currency_identifiers['GYD'] = Currency(u'$', u'Guyana Dollar')
currency_identifiers['HKD'] = Currency(u'HK$', u'Hong Kong Dollar')
currency_identifiers['HNL'] = Currency(u'L', u'Lempira')
currency_identifiers['HRK'] = Currency(u'kn', u'Croatian Kuna')
currency_identifiers['HTG'] = Currency(u'', u'Gourde')
currency_identifiers['HUF'] = Currency(u'Ft', u'Forint')
currency_identifiers['IDR'] = Currency(u'Rp', u'Rupiah')
currency_identifiers['ILS'] = Currency(u'₪', u'New Israeli Sheqel')
currency_identifiers['INR'] = Currency(u'', u'Indian Rupee')
currency_identifiers['IQD'] = Currency(u'', u'Iraqi Dinar')
currency_identifiers['IRR'] = Currency(u'﷼', u'Iranian Rial')
currency_identifiers['ISK'] = Currency(u'kr', u'Iceland Krona')
currency_identifiers['JMD'] = Currency(u'J$', u'Jamaican Dollar')
currency_identifiers['JOD'] = Currency(u'', u'Jordanian Dinar')
currency_identifiers['JPY'] = Currency(u'¥', u'Yen')
currency_identifiers['KES'] = Currency(u'', u'Kenyan Shilling')
currency_identifiers['KGS'] = Currency(u'лв', u'Som')
currency_identifiers['KHR'] = Currency(u'៛', u'Riel')
currency_identifiers['KMF'] = Currency(u'', u'Comoro Franc')
currency_identifiers['KPW'] = Currency(u'₩', u'North Korean Won')
currency_identifiers['KRW'] = Currency(u'₩', u'Won')
currency_identifiers['KWD'] = Currency(u'', u'Kuwaiti Dinar')
currency_identifiers['KYD'] = Currency(u'$', u'Cayman Islands Dollar')
currency_identifiers['KZT'] = Currency(u'лв', u'Tenge')
currency_identifiers['LAK'] = Currency(u'₭', u'Kip')
currency_identifiers['LBP'] = Currency(u'£', u'Lebanese Pound')
currency_identifiers['LKR'] = Currency(u'₨', u'Sri Lanka Rupee')
currency_identifiers['LRD'] = Currency(u'$', u'Liberian Dollar')
currency_identifiers['LSL'] = Currency(u'', u'Loti')
currency_identifiers['LTL'] = Currency(u'Lt', u'Lithuanian Litas')
currency_identifiers['LVL'] = Currency(u'Ls', u'Latvian Lats')
currency_identifiers['LYD'] = Currency(u'', u'Libyan Dinar')
currency_identifiers['MAD'] = Currency(u'', u'Moroccan Dirham')
currency_identifiers['MDL'] = Currency(u'', u'Moldovan Leu')
currency_identifiers['MGA'] = Currency(u'', u'Malagasy Ariary')
currency_identifiers['MKD'] = Currency(u'ден', u'Denar')
currency_identifiers['MMK'] = Currency(u'', u'Kyat')
currency_identifiers['MNT'] = Currency(u'₮', u'Tugrik')
currency_identifiers['MOP'] = Currency(u'', u'Pataca')
currency_identifiers['MRO'] = Currency(u'', u'Ouguiya')
currency_identifiers['MUR'] = Currency(u'₨', u'Mauritius Rupee')
currency_identifiers['MVR'] = Currency(u'', u'Rufiyaa')
currency_identifiers['MWK'] = Currency(u'', u'Kwacha')
currency_identifiers['MXN'] = Currency(u'$', u'Mexican Peso')
currency_identifiers['MXV'] = Currency(u'', u'Mexican Unidad de Inversion (UDI)')
currency_identifiers['MYR'] = Currency(u'RM', u'Malaysian Ringgit')
currency_identifiers['MZN'] = Currency(u'MT', u'Mozambique Metical')
currency_identifiers['NAD'] = Currency(u'$', u'Namibia Dollar')
currency_identifiers['NGN'] = Currency(u'₦', u'Naira')
currency_identifiers['NIO'] = Currency(u'C$', u'Cordoba Oro')
currency_identifiers['NOK'] = Currency(u'kr', u'Norwegian Krone')
currency_identifiers['NPR'] = Currency(u'₨', u'Nepalese Rupee')
currency_identifiers['NZD'] = Currency(u'$', u'New Zealand Dollar')
currency_identifiers['OMR'] = Currency(u'﷼', u'Rial Omani')
currency_identifiers['PAB'] = Currency(u'B/.', u'Balboa')
currency_identifiers['PEN'] = Currency(u'S/.', u'Nuevo Sol')
currency_identifiers['PGK'] = Currency(u'', u'Kina')
currency_identifiers['PHP'] = Currency(u'₱', u'Philippine Peso')
currency_identifiers['PKR'] = Currency(u'₨', u'Pakistan Rupee')
currency_identifiers['PLN'] = Currency(u'zł', u'Zloty')
currency_identifiers['PYG'] = Currency(u'Gs', u'Guarani')
currency_identifiers['QAR'] = Currency(u'﷼', u'Qatari Rial')
currency_identifiers['RON'] = Currency(u'lei', u'New Romanian Leu')
currency_identifiers['RSD'] = Currency(u'Дин.', u'Serbian Dinar')
currency_identifiers['RUB'] = Currency(u'руб', u'Russian Ruble')
currency_identifiers['RWF'] = Currency(u'', u'Rwanda Franc')
currency_identifiers['SAR'] = Currency(u'﷼', u'Saudi Riyal')
currency_identifiers['SBD'] = Currency(u'$', u'Solomon Islands Dollar')
currency_identifiers['SCR'] = Currency(u'₨', u'Seychelles Rupee')
currency_identifiers['SDG'] = Currency(u'', u'Sudanese Pound')
currency_identifiers['SEK'] = Currency(u'kr', u'Swedish Krona')
currency_identifiers['SGD'] = Currency(u'$', u'Singapore Dollar')
currency_identifiers['SHP'] = Currency(u'£', u'Saint Helena Pound')
currency_identifiers['SLL'] = Currency(u'', u'Leone')
currency_identifiers['SOS'] = Currency(u'S', u'Somali Shilling')
currency_identifiers['SRD'] = Currency(u'$', u'Surinam Dollar')
currency_identifiers['SSP'] = Currency(u'', u'South Sudanese Pound')
currency_identifiers['STD'] = Currency(u'', u'Dobra')
currency_identifiers['SVC'] = Currency(u'$', u'El Salvador Colon')
currency_identifiers['SYP'] = Currency(u'£', u'Syrian Pound')
currency_identifiers['SZL'] = Currency(u'', u'Lilangeni')
currency_identifiers['THB'] = Currency(u'฿', u'Baht')
currency_identifiers['TJS'] = Currency(u'', u'Somoni')
currency_identifiers['TMT'] = Currency(u'', u'Turkmenistan New Manat')
currency_identifiers['TND'] = Currency(u'', u'Tunisian Dinar')
currency_identifiers['TOP'] = Currency(u'', u'Pa’anga')
currency_identifiers['TRY'] = Currency(u'TL', u'Turkish Lira')
currency_identifiers['TTD'] = Currency(u'TT$', u'Trinidad and Tobago Dollar')
currency_identifiers['TWD'] = Currency(u'NT$', u'New Taiwan Dollar')
currency_identifiers['TZS'] = Currency(u'', u'Tanzanian Shilling')
currency_identifiers['UAH'] = Currency(u'₴', u'Hryvnia')
currency_identifiers['UGX'] = Currency(u'', u'Uganda Shilling')
currency_identifiers['USD'] = Currency(u'$', u'US Dollar')
currency_identifiers['USN'] = Currency(u'$', u'US Dollar (Next day)')
currency_identifiers['USS'] = Currency(u'$', u'US Dollar (Same day)')
currency_identifiers['UYI'] = Currency(u'', u'Uruguay Peso en Unidades Indexadas (URUIURUI)')
currency_identifiers['UYU'] = Currency(u'$U', u'Peso Uruguayo')
currency_identifiers['UZS'] = Currency(u'лв', u'Uzbekistan Sum')
currency_identifiers['VEF'] = Currency(u'Bs', u'Bolivar Fuerte')
currency_identifiers['VND'] = Currency(u'₫', u'Dong')
currency_identifiers['VUV'] = Currency(u'', u'Vatu')
currency_identifiers['WST'] = Currency(u'', u'Tala')
currency_identifiers['XAF'] = Currency(u'', u'CFA Franc BEAC')
currency_identifiers['XAG'] = Currency(u'', u'Silver')
currency_identifiers['XAU'] = Currency(u'', u'Gold')
currency_identifiers['XBA'] = Currency(u'', u'Bond Markets Unit European Composite Unit (EURCO)')
currency_identifiers['XBB'] = Currency(u'', u'Bond Markets Unit European Monetary Unit (E.M.U.-6)')
currency_identifiers['XBC'] = Currency(u'', u'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)')
currency_identifiers['XBD'] = Currency(u'', u'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)')
currency_identifiers['XCD'] = Currency(u'$', u'East Caribbean Dollar')
currency_identifiers['XDR'] = Currency(u'', u'SDR (Special Drawing Right)')
currency_identifiers['XFU'] = Currency(u'', u'UIC-Franc')
currency_identifiers['XOF'] = Currency(u'', u'CFA Franc BCEAO')
currency_identifiers['XPD'] = Currency(u'', u'Palladium')
currency_identifiers['XPF'] = Currency(u'', u'CFP Franc')
currency_identifiers['XPT'] = Currency(u'', u'Platinum')
currency_identifiers['XSU'] = Currency(u'', u'Sucre')
currency_identifiers['XUA'] = Currency(u'', u'ADB Unit of Account')
currency_identifiers['YER'] = Currency(u'﷼', u'Yemeni Rial')
currency_identifiers['ZAR'] = Currency(u'R', u'Rand')
currency_identifiers['ZMK'] = Currency(u'', u'Zambian Kwacha')
currency_identifiers['ZWL'] = Currency(u'', u'Zimbabwe Dollar')
